remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: EMG for Control
description: Using easily acquired EMG sensors as well as other sensors and tools we created several datasets that will be free to use under the {license name} license. 
show_downloads: true
